DOMAIN_FIXES = {
    # 'accenture.com': None,
    # 'aist.enst.fr': None,
    # 'aliceadsl.fr': None,
    # 'ann.jussieu.fr': None,
    # 'aol.com': None,
    # 'aphp.fr': None,
    # 'april.org': None,
    # 'assemblee-nationale.fr': None,
    # 'bbox.fr': None,
    # 'bers.tel': None,
    # 'bouzy.org': None,
    # 'capdepuy.net': None,
    # 'cegetel.net': None,
    # 'centuria.net': None,
    # 'club-internet.fr': None,
    # 'crans.org': None,
    # 'djerem.net': None,
    # 'ens.fr': None,
    # 'enst.fr': None,
    # 'ensta.fr': None,
    # 'ensta.org': None,
    # 'espci.org': None,
    # 'essec.edu': None,
    # 'fr.ibm.com': None,
    # 'free.fr': None,
    # 'fundimmo.com': None,
    # 'gagnon.fr': None,
    # 'garnier.wf': None,
    # 'gazeta.pl': None,
    # 'glac.de': None,
    # 'glouglou.org': None,
    # 'gmail.com ': None,
    # 'gmail.com': None,
    # 'gmx.com': None,
    # 'hec.ca': None,
    # 'hec.edu': None,
    # 'hotmail.com': None,
    # 'hotmail.fr': None,
    # 'imcce.fr': None,
    # 'institutoptique.fr': None,
    # 'laposte.net': None,
    # 'libertysurf.fr': None,
    # 'live.fr': None,
    # 'm4x.org': None,
    # 'neuf.fr': None,
    # 'noos.fr': None,
    # 'orange.fr': None,
    # 'outlook.com': None,
    # 'pharipou.net': None,
    # 'pigments-bleu.com': None,
    # 'polytechnique.org': None,
    # 'pps.univ-paris-diderot.fr': None,
    # 'sap.aphp.fr': None,
    # 'sciencespo.fr': None,
    # 'sfr.fr': None,
    # 'toufik-menguellati.fr': None,
    # 'univ-mlv.fr': None,
    # 'univ-paris12.fr': None,
    # 'upmc.fr': None,
    # 'wanadoo.fr': None,
    # 'yahoo.ca': None,
    # 'yahoo.com': None,
    # 'yahoo.fr': None,
    'Chatzi.Org': None,
    'Dufx.Com': None,
    'Ens-Lsh.Org': None,
    'Free.Fr': 'free.fr',
    'GMAIL.COM': 'gmail.com',
    'GMAILCOM': 'gmail.com',
    'Gmail.Com': 'gmail.com',
    'HOTMAIL.FR': 'hotmail.fr',
    'Hotmail.Com': 'hotmail.com',
    'Hotmail.Fr': 'hotmail.fr',
    'Mamber.Net': None,
    'Neuf.Fr': 'neuf.fr',
    'Orange.Fr': 'orange.fr',
    'Outlook.Fr': 'outlook.fr',
    'Wanadoo.Fr': 'wanadoo.fr',
    'YAHOO.FR': 'yahoo.fr',
    'Yahoo.Com': 'yahoo.com',
    'Yahoo.Fr': 'yahoo.fr',
    'Zeuxis.Net': None,
    'gmail.Com': 'gmail.com',
    'yahoo.Fr': None,
    'ymail.com': None,
}

####################################################################################################

# http://www.lemur-escalade.org/le-club
# http://roc14.org

CLUB_FIXES = {
    'LE MUR': 'Le Mur',
    'ROC14': 'Roc 14',
    'ROC 14': 'Roc 14',
}
