####################################################################################################
#
# Climbing Asso Portal - A Portal for Climbing Club (Association)
# Copyright (C) 2018 Fabrice Salvaire
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
####################################################################################################

####################################################################################################

"""Django settings for Climbing Asso Portal project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/

"""

####################################################################################################

from pathlib import Path

from django.conf import settings
# from django_jinja.builtins import DEFAULT_EXTENSIONS

####################################################################################################
#
# Debug
#

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

####################################################################################################

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = Path(__file__).resolve().parents[1]

####################################################################################################

ROOT_URLCONF = 'ClimbingAssoPortalSite.urls'

WSGI_APPLICATION = 'ClimbingAssoPortalSite.wsgi.application'

SITE_ID = 1

ALLOWED_HOSTS = []

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#v2=-7xr3=5(^63sc4)374j48j-d23bo4gc%z$+a#nji56k%we'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = str(BASE_DIR.joinpath('static'))
MEDIA_URL = '/filer_public/'
# MEDIA_ROOT = str(BASE_DIR.joinpath('filer_public'))
MEDIA_ROOT = str(BASE_DIR)

####################################################################################################
#
# Database
#

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': str(BASE_DIR.joinpath('db.sqlite3')),
    }
}

####################################################################################################
#
# Application definition
#

INSTALLED_APPS = [
    # /!\ ordered list
    'suit', # must be added before admin
    # http://django-suit.readthedocs.io/en/develop
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django.contrib.sites',

    'rest_framework', # http://www.django-rest-framework.org
    'rest_framework_swagger', # https://django-rest-swagger.readthedocs.io/en/latest
    'drf_yasg', # https://github.com/axnsan12/drf-yasg

    'reversion', # https://django-reversion.readthedocs.io/en/stable

    'django_jinja', # http://niwinz.github.io/django-jinja/latest
    'bootstrapform', # https://github.com/tzangms/django-bootstrap-form

    'django_select2', # http://django-select2.readthedocs.io/en/latest

    # 'pinax_theme_bootstrap', # https://github.com/pinax/pinax-theme-bootstrap
    'account', # http://django-user-accounts.readthedocs.io/en/latest

    # https://django-filer.readthedocs.io
    'easy_thumbnails',
    'filer',
    'mptt',

     # http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html#using-celery-with-django
    'django_celery_results', # http://django-celery-results.readthedocs.io/en/latest/
    'django_celery_beat', # http://django-celery-beat.readthedocs.io/en/latest/

    'ClimbingAssoPortal',

    # https://github.com/applecat/django-simple-poll
    # https://github.com/byteweaver/django-polls
    # https://github.com/hmtanbir/django-easy-poll
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'account.middleware.LocaleMiddleware',
    'account.middleware.TimezoneMiddleware',
    'account.middleware.ExpiredPasswordMiddleware',
]

####################################################################################################
#
# Template
#

TEMPLATES = [
    {
        'BACKEND': 'django_jinja.backend.Jinja2',
        # 'BACKEND': 'django.template.backends.jinja2.Jinja2',
        'APP_DIRS': True, # looks for app/jinja2
        'OPTIONS': {
            "app_dirname": "jinja2",
            # 'match_extension': '.jinja',
            # 'match_extension': '.html',
            'match_extension': None,
            'match_regex': r"^(?!admin/).*", # \.(html|txt)$

            'newstyle_gettext': True,

            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'account.context_processors.account',
                'ClimbingAssoPortal.context_processors.site',
            ],

            'extensions': [
                'jinja2.ext.do',
                'jinja2.ext.loopcontrols',
                'jinja2.ext.with_',
                'jinja2.ext.i18n',
                'jinja2.ext.autoescape',
                'django_jinja.builtins.extensions.CsrfExtension',
                'django_jinja.builtins.extensions.CacheExtension',
                'django_jinja.builtins.extensions.TimezoneExtension',
                'django_jinja.builtins.extensions.UrlsExtension',
                'django_jinja.builtins.extensions.StaticFilesExtension',
                'django_jinja.builtins.extensions.DjangoFiltersExtension',
            ],

            'bytecode_cache': {
                'name': 'default',
                'backend': 'django_jinja.cache.BytecodeCache',
                'enabled': False,
            },
            'autoescape': True,
            'auto_reload': settings.DEBUG,
            'translation_engine': 'django.utils.translation',
            "globals": {
                # 'urlnext': 'ClimbingAssoPortal.JinjaExtension.account',
            },
        },
    },
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [],
        'DIRS': [
            'filer/templates',
            'ClimbingAssoPortal/templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'account.context_processors.account',
                # 'pinax_theme_bootstrap.context_processors.theme',
            ],
        },
    },
]

####################################################################################################
#
# Password validation
#

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

# Fixme: Not in production !
AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]

####################################################################################################
#
# Internationalization
#

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

####################################################################################################
#
# Django Suit configuration
#

SUIT_CONFIG = {
    # header
    'ADMIN_NAME': 'Climbing Asso Portal',
    'HEADER_DATE_FORMAT': 'l, j F Y',
    'HEADER_TIME_FORMAT': 'H:i',

    # forms
    'SHOW_REQUIRED_ASTERISK': True,
    'CONFIRM_UNSAVED_CHANGES': True,

    'LIST_PER_PAGE': 15
}

####################################################################################################
#
# REST Framework
#

REST_FRAMEWORK = {
    # http://www.django-rest-framework.org/api-guide/permissions/
    'DEFAULT_PERMISSION_CLASSES': (
        # DjangoModelPermissionsOrAnonReadOnly
        # 'rest_framework.permissions.IsAuthenticatedOrReadOnly',
        # 'rest_framework.permissions.IsAuthenticated',
        'rest_framework.permissions.IsAdminUser',
    ),

    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 100,
}

# cf. https://django-rest-swagger.readthedocs.io/en/latest/settings/
SWAGGER_SETTINGS = {
}

####################################################################################################
#
# Email
#

# Log to console
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

####################################################################################################
#
# Account
#

ACCOUNT_EMAIL_CONFIRMATION_REQUIRED = True
ACCOUNT_DELETION_MARK_CALLBACK = None # Fixme:
THEME_CONTACT_EMAIL = 'admin@foo.org'

####################################################################################################
#
# Easy Thumbail
#

# THUMBNAIL_PROCESSORS = (
#     'easy_thumbnails.processors.colorspace',
#     'easy_thumbnails.processors.autocrop',
#     #'easy_thumbnails.processors.scale_and_crop',
#     'filer.thumbnail_processors.scale_and_crop_with_subject_location',
#     'easy_thumbnails.processors.filters',
# )

####################################################################################################
#
# Filer
#

# FILER_ENABLE_PERMISSIONS = False
# Activate the or not the Permission check on the files and folders before displaying them in the
# admin. When set to False it gives all the authorization to staff members based on standard Django
# model permissions.

# FILER_IS_PUBLIC_DEFAULT = True
# Should newly uploaded files have permission checking disabled (be public) by default.

# FILER_STORAGES
# A dictionary to configure storage backends used for file storage.

# FILER_PAGINATE_BY = 20
# The number of items (Folders, Files) that should be displayed per page in admin.

# FILER_SUBJECT_LOCATION_IMAGE_DEBUG = False
# Draws a red circle around to point in the image that was used to do the subject location aware
# image cropping.

# FILER_ALLOW_REGULAR_USERS_TO_ADD_ROOT_FOLDERS = False
# Regular users are not allowed to create new folders at the root level, only subfolders of already
# existing folders, unless this setting is set to True.

# FILER_IMAGE_MODEL = False
# Defines the dotted path to a custom Image model; please include the model name. Example:
# ‘my.app.models.CustomImage’

# FILER_CANONICAL_URL = 'canonical/'
# Defines the path element common to all canonical file URLs.

# FILER_UPLOADER_CONNECTIONS = 3
# Number of simultaneous AJAX uploads. Defaults to 3.

####################################################################################################
#
# Celery
#

CELERY_BROKER_URL='pyamqp://guest@localhost//'

# CELERY_RESULT_BACKEND = 'django-db'
# CELERY_RESULT_BACKEND = 'django-cache'

####################################################################################################
#
# Google API
#

GOOGLE_API_CREDENTIAL_DIR = BASE_DIR.joinpath('.google-api-credentials')
GOOGLE_API_APPLICATION_NAME = 'Climbing Asso Portal'
GOOGLE_API_ROUTE_SPREADSHEET_ID = '1xzzypnm80bUooj8ZPMLhtYEQbZtL89QpIBBNFXn5y90'
GOOGLE_API_ROUTE_SHEET = 'Liste des voies'

####################################################################################################
#
# Cache
#

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
    }
}

# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
#         'LOCATION': '127.0.0.1:11211',
#         'LOCATION': 'unix:/tmp/memcached.sock',
#     }
# }
