#! /usr/bin/env python3

####################################################################################################

import random

####################################################################################################

characters = 'abcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*(-_=+)'
key_length = 50

key = ''.join([random.SystemRandom().choice(characters) for i in range(key_length)])

print(key)
