#! /usr/bin/env python3

####################################################################################################
#
# Climbing Asso Portal - A Portal for Climbing Club (Association)
# Copyright (C) 2018 Fabrice Salvaire
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
####################################################################################################

####################################################################################################
#
# See also ./manage.py makemessages
#   but --exclude is tricky
#
####################################################################################################

####################################################################################################

from pathlib import Path
import argparse
import os
import subprocess

####################################################################################################

parser = argparse.ArgumentParser(description='Make Translation.')
parser.add_argument('--init', action='store_true')
parser.add_argument('--update', action='store_true')
parser.add_argument('--compile', action='store_true')

args = parser.parse_args()

####################################################################################################

source_path = Path(__file__).parents[1].resolve()
locale_dir = source_path.joinpath('ClimbingAssoPortal', 'locale')
babel_cfg_path = locale_dir.joinpath('babel.cfg')
message_pot_path = locale_dir.joinpath('messages.pot')

domain = 'ClimbingAssoPortal'

####################################################################################################

if args.update:
    # Extract localizable messages from a collection of source files
    subprocess.call(('pybabel', 'extract',
                     '-F', babel_cfg_path,   # path to the extraction mapping file
                     '-k', 'lazy_gettext',   # keywords to look for in addition to the defaults
                     '-o', message_pot_path, # path to the output POT file
                     source_path))

    if args.init:
        for language in ('en', 'fr'):
            if not locale_dir.joinpath(language, 'LC_MESSAGES', 'portal.po').exists:
                # Create a new translations catalog based on a PO template file
                subprocess.call(('pybabel', 'init',
                                 '-D', domain,           # domain of PO file (default 'messages')
                                 '-i', message_pot_path, # name of the input file
                                 '-d', locale_dir,       # path to output directory
                                 '-l', language))        # locale for the new localized catalog

    # Update an existing new translations catalog based on a PO template file
    subprocess.call(('pybabel', 'update',
                     '-D', domain,
                     '-i', message_pot_path,
                     '-d', locale_dir))

if args.compile:
    subprocess.call(('pybabel', 'compile',
                     '-D', domain,
                     '-d', locale_dir))

# poedit
# linguist-qt5
